[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
    "setuptools_scm>=6.0",
    "tomli",  # Required for setuptools_scm to read pyproject.toml
    "spacy>=3.7.0,<3.8.0",
    "en-core-web-lg @ https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.7.0/en_core_web_lg-3.7.0-py3-none-any.whl",
    "ja_core_news_lg @ https://github.com/explosion/spacy-models/releases/download/ja_core_news_lg-3.7.0/ja_core_news_lg-3.7.0-py3-none-any.whl"
]
build-backend = "setuptools.build_meta"


[project]
name = "kairyou"
version = "v0.0.4"
authors = [
  { name="Bikatr7", email="Tetalon07@gmail.com" },
]
description = "A Japanese preprocessor"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3.8",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Bikatr7/Kairyou"
Issues = "https://github.com/Bikatr7/Kairyou/issues"